---
- name: Copy Required File and Folder to DocumentRoot of the Site
  copy:
    src: "{{ copy_frm_location }}/{{ item }}"
    dest: "{{ site_documentroot }}"
  with_items:
    - images
    - plugins
    - js
    - styles
    - .htaccess



- name: Copy Index file  using jinja template
  template:
    src: index.html.j2
    dest: "{{ site_documentroot }}/index.html"
    mode: 0644
    
